//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListPlayers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ListPlayers.Properties.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите папку с файлами для обработки:.
        /// </summary>
        internal static string BrowserSelectSourceFolder {
            get {
                return ResourceManager.GetString("BrowserSelectSourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена транзакции....
        /// </summary>
        internal static string CancellingTransaction {
            get {
                return ResourceManager.GetString("CancellingTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершение транзакции....
        /// </summary>
        internal static string CommittingTransaction {
            get {
                return ResourceManager.GetString("CommittingTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сжатие....
        /// </summary>
        internal static string Compressing {
            get {
                return ResourceManager.GetString("Compressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База данных повреждена..
        /// </summary>
        internal static string CorruptedDatabase {
            get {
                return ResourceManager.GetString("CorruptedDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  файл успешно обработан..
        /// </summary>
        internal static string FilesProcessedX1 {
            get {
                return ResourceManager.GetString("FilesProcessedX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  файла успешно обработаны..
        /// </summary>
        internal static string FilesProcessedX234 {
            get {
                return ResourceManager.GetString("FilesProcessedX234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  файлов успешно обработаны..
        /// </summary>
        internal static string FilesProcessedXX {
            get {
                return ResourceManager.GetString("FilesProcessedXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этот фильтр чувствителен к регистру. Для игнорирования регистра
        ///добавьте по символу % в начало и конец каждой строки..
        /// </summary>
        internal static string FilterIsCaseSensetive {
            get {
                return ResourceManager.GetString("FilterIsCaseSensetive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск не дал результатов..
        /// </summary>
        internal static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открытие транзакции....
        /// </summary>
        internal static string OpeningTransaction {
            get {
                return ResourceManager.GetString("OpeningTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите файл базы данных..
        /// </summary>
        internal static string SelectDatabaseFile {
            get {
                return ResourceManager.GetString("SelectDatabaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный файл не найден..
        /// </summary>
        internal static string SelectedFileNotFound {
            get {
                return ResourceManager.GetString("SelectedFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранная папка не содержит файлов допустимого формата..
        /// </summary>
        internal static string SelectedFolderDoesntContainAcceptedFiles {
            get {
                return ResourceManager.GetString("SelectedFolderDoesntContainAcceptedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранная папка не найдена..
        /// </summary>
        internal static string SelectedFolderNotFound {
            get {
                return ResourceManager.GetString("SelectedFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите папку с файлами для обработки..
        /// </summary>
        internal static string SelectSourceFolder {
            get {
                return ResourceManager.GetString("SelectSourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текстовые документы.
        /// </summary>
        internal static string TextDocuments {
            get {
                return ResourceManager.GetString("TextDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транзакция отменена.
        /// </summary>
        internal static string TransactionCancelled {
            get {
                return ResourceManager.GetString("TransactionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработка завершена.
        /// </summary>
        internal static string UpdateCompleted {
            get {
                return ResourceManager.GetString("UpdateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление базы.
        /// </summary>
        internal static string UpdatingDatabase {
            get {
                return ResourceManager.GetString("UpdatingDatabase", resourceCulture);
            }
        }
    }
}
